# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcAU519nxA0pxYaWLc2YiOJL39r9N4PE
"""

import sys
import argparse
import math
import numpy as np
import cv2
import jetson_utils
from jetson_inference import poseNet
from jetson_utils import videoSource, videoOutput

# ---------------- ARGUMENTS ----------------
parser = argparse.ArgumentParser()
parser.add_argument("input", type=str, help="Input image/video")
parser.add_argument("output", type=str, help="Output image/video or display")
parser.add_argument("--network", type=str, default="resnet18-body")
parser.add_argument("--overlay", type=str, default="links,keypoints")
parser.add_argument("--threshold", type=float, default=0.15)
args = parser.parse_args()

# Load PoseNet model
net = poseNet(args.network, sys.argv, args.threshold)

# Create video input/output objects
input = videoSource(args.input, argv=sys.argv)
output = videoOutput(args.output, argv=sys.argv)

while True:
    img = input.Capture()
    if img is None:
        continue  # skip if nothing captured

    # Run pose estimation
    poses = net.Process(img, overlay=args.overlay)
    centers, bboxes = [], []

    # Get center point of each person
    for pose in poses:
        kp = pose.Keypoints
        def safe_kp(i): return kp[i] if i < len(kp) else None

        left_hip, right_hip = safe_kp(11), safe_kp(12)
        left_sh, right_sh = safe_kp(5), safe_kp(6)

        if left_hip and right_hip:
            cx, cy = int((left_hip.x + right_hip.x)/2), int((left_hip.y + right_hip.y)/2)
        elif left_sh and right_sh:
            cx, cy = int((left_sh.x + right_sh.x)/2), int((left_sh.y + right_sh.y)/2)
        else:
            cx, cy = int((pose.Left + pose.Right)/2), int((pose.Top + pose.Bottom)/2)

        centers.append((cx, cy))
        bboxes.append((pose.Left, pose.Top, pose.Right, pose.Bottom))

    # ---------------- DISTANCE CHECK ----------------
    violations = []
    person_status = ["SAFE"] * len(centers)

    for i in range(len(centers)):
        for j in range(i+1, len(centers)):
            (x1, y1), (x2, y2) = centers[i], centers[j]
            pixel_dist = math.dist((x1, y1), (x2, y2))

            L, T, R, B = bboxes[i]
            height_px = max(abs(B - T), 50)
            meters_per_pixel = 1.7 / height_px
            meter_dist = pixel_dist * meters_per_pixel

            if meter_dist < 2.0:  # too close
                violations.append((i, j))
                person_status[i] = person_status[j] = "DANGER"

    # Convert GPU image to NumPy for drawing
    cv_img = jetson_utils.cudaToNumpy(img)

    # Draw lines between people
    for (i, j) in violations:
        cv2.line(cv_img, centers[i], centers[j], (0, 0, 255), 3)  # red = danger
    for i in range(len(centers)):
        for j in range(i+1, len(centers)):
            if (i, j) not in violations:
                cv2.line(cv_img, centers[i], centers[j], (0, 255, 0), 2)  # green = safe

    # Draw bounding boxes and labels
    for idx, ((L, T, R, B), status) in enumerate(zip(bboxes, person_status)):
        L, T, R, B = int(L), int(T), int(R), int(B)  # OpenCV needs ints
        color = (0, 0, 255) if status == "DANGER" else (0, 255, 0)
        cv2.rectangle(cv_img, (L, T), (R, B), color, 2)
        cv2.putText(cv_img, f"ID:{idx} {status}", (L, T-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

    # Summary text
    cv2.putText(cv_img, f"People: {len(centers)} | Violations: {len(violations)}",
                (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)

    # Convert back to GPU and display
    img_overlay = jetson_utils.cudaFromNumpy(cv_img)
    output.Render(img_overlay)

    # Save output if specified as image
    if args.output.endswith(".jpg") or args.output.endswith(".png"):
        cv2.imwrite(args.output, cv_img)

    # Show FPS in window title
    output.SetStatus(f"{args.network} | FPS: {net.GetNetworkFPS():.0f}")

    if not input.IsStreaming() or not output.IsStreaming():
        break